package com.anythink.expressad.video.dynview.a;

/* loaded from: classes2.dex */
public final class a {
    public static final String A = "Automatische Wiedergabe nach ";
    public static final String B = " 초 후 자동 재생 ";
    public static final String C = "Lecture de vidéo dans ";
    public static final String D = "لعب تلقائيا بعد ";
    public static final String E = "Автовоспроизведение через ";
    public static final String F = "猜你喜欢";
    public static final String G = "Just\nfor\nYou";
    public static final String H = "anythink_reward_two_title_";
    public static final String I = "alecfc";
    public static final String J = "1";
    public static final String K = "0";
    public static final String L = "_por";
    public static final String M = "_land";
    public static final String N = "zh";
    public static final String O = "ja";
    public static final String P = "de";
    public static final String Q = "ko";
    public static final String R = "fr";
    public static final String S = "ar";
    public static final String T = "ru";
    public static final String U = "en";
    public static final String V = "TW";
    public static final String W = "HK";
    public static final String a = "anythink_reward_end_card_layout_landscape";
    public static final String b = "anythink_reward_end_card_layout_portrait";
    public static final String c = "anythink_reward_layer_floor";
    public static final String d = "anythink_reward_layer_floor";
    public static final String e = "anythink_reward_layer_floor_302";
    public static final String f = "anythink_reward_layer_floor_802";
    public static final String g = "anythink_reward_layer_floor";
    public static final String h = "anythink_reward_layer_floor_bottom";
    public static final String i = "anythink_same_choice_one_layout_landscape";
    public static final String j = "anythink_same_choice_one_layout_portrait";
    public static final int k = -1;
    public static final int l = 1;
    public static final int m = 102;
    public static final int n = 202;
    public static final int o = 302;
    public static final int p = 802;
    public static final int q = 904;
    public static final int r = 3;
    public static final int s = 4;
    public static final int t = 404;
    public static final int u = 704;
    public static final String v = "choice_one_callback";
    public static final String w = " 秒后自动播放";
    public static final String x = " 秒後自動播放";
    public static final String y = "Auto play after ";
    public static final String z = " 秒後自動的に再生 ";
}