package com.p7700g.p99005;

import android.os.Parcel;
import com.anythink.core.api.ATAdConst;
import org.jetbrains.annotations.NotNull;

/* compiled from: Parceler.kt */
@vo4(bv = {1, 0, 3}, d1 = {"\u0000&\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\b\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0005\n\u0002\u0010\u0011\n\u0002\b\u0003\bf\u0018\u0000*\u0004\b\u0000\u0010\u00012\u00020\u0002J#\u0010\b\u001a\u00020\u0007*\u00028\u00002\u0006\u0010\u0004\u001a\u00020\u00032\u0006\u0010\u0006\u001a\u00020\u0005H&¢\u0006\u0004\b\b\u0010\tJ\u0017\u0010\n\u001a\u00028\u00002\u0006\u0010\u0004\u001a\u00020\u0003H&¢\u0006\u0004\b\n\u0010\u000bJ\u001d\u0010\u000e\u001a\b\u0012\u0004\u0012\u00028\u00000\r2\u0006\u0010\f\u001a\u00020\u0005H\u0016¢\u0006\u0004\b\u000e\u0010\u000f¨\u0006\u0010"}, d2 = {"Lcom/p7700g/p99005/ka5;", "T", "", "Landroid/os/Parcel;", "parcel", "", "flags", "Lcom/p7700g/p99005/yq4;", "a", "(Ljava/lang/Object;Landroid/os/Parcel;I)V", "b", "(Landroid/os/Parcel;)Ljava/lang/Object;", ATAdConst.NETWORK_REQUEST_PARAMS_KEY.BANNER_SIZE, "", "newArray", "(I)[Ljava/lang/Object;", "kotlin-android-extensions-runtime"}, k = 1, mv = {1, 5, 1})
/* loaded from: classes3.dex */
public interface ka5<T> {

    /* compiled from: Parceler.kt */
    @vo4(bv = {1, 0, 3}, d1 = {}, d2 = {}, k = 3, mv = {1, 5, 1})
    /* loaded from: classes3.dex */
    public static final class a {
        @NotNull
        public static <T> T[] a(@NotNull ka5<T> ka5Var, int i) {
            c25.p(ka5Var, "this");
            throw new xo4("Generated by Android Extensions automatically");
        }
    }

    void a(T t, @NotNull Parcel parcel, int i);

    T b(@NotNull Parcel parcel);

    @NotNull
    T[] newArray(int i);
}