package com.microsoft.appcenter.crashes.model;

import com.p7700g.p99005.r2;

/* loaded from: classes3.dex */
public class TestCrashException extends RuntimeException {
    @r2
    public static final String CRASH_MESSAGE = "Test crash exception generated by SDK";

    public TestCrashException() {
        super(CRASH_MESSAGE);
    }
}